name: Continuous Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  CLUSTER: briklabs-eks-cluster
  REGION: us-east-1
  NAMESPACE: apps-template
  SERVICE: cms

jobs:
  deploy:
    name: Deploy Wordpress CMS With MySQL DB
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}

      - name: helm deploy
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
        with:
          aws-region: ${{env.REGION}}
          cluster-name: ${{env.CLUSTER}}
          chart-repository: oci://registry-1.docker.io
          chart-path: bitnamicharts/wordpress
          namespace: ${{env.NAMESPACE}}
          name: ${{env.SERVICE}}

